//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Review.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Review.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 始终校验批次码 的本地化字符串。
        /// </summary>
        internal static string alwaysVerification {
            get {
                return ResourceManager.GetString("alwaysVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始生产 的本地化字符串。
        /// </summary>
        internal static string btnStart {
            get {
                return ResourceManager.GetString("btnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止生产 的本地化字符串。
        /// </summary>
        internal static string btnStop {
            get {
                return ResourceManager.GetString("btnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [切换语言] 的本地化字符串。
        /// </summary>
        internal static string buttonChangeLanguage {
            get {
                return ResourceManager.GetString("buttonChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用批次码校验 的本地化字符串。
        /// </summary>
        internal static string EnableVerification {
            get {
                return ResourceManager.GetString("EnableVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 质量追溯系统 的本地化字符串。
        /// </summary>
        internal static string frmMain {
            get {
                return ResourceManager.GetString("frmMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部件名称 的本地化字符串。
        /// </summary>
        internal static string FscAddtitle {
            get {
                return ResourceManager.GetString("FscAddtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加数据行 的本地化字符串。
        /// </summary>
        internal static string FscbtnAdd {
            get {
                return ResourceManager.GetString("FscbtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存数据 的本地化字符串。
        /// </summary>
        internal static string FscbtnSave {
            get {
                return ResourceManager.GetString("FscbtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验 的本地化字符串。
        /// </summary>
        internal static string Fvscbtncheck {
            get {
                return ResourceManager.GetString("Fvscbtncheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string Fvscbtnsure {
            get {
                return ResourceManager.GetString("Fvscbtnsure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 档次号 的本地化字符串。
        /// </summary>
        internal static string FvscLabelgrade {
            get {
                return ResourceManager.GetString("FvscLabelgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 型号选择 的本地化字符串。
        /// </summary>
        internal static string FvscLabelinfo {
            get {
                return ResourceManager.GetString("FvscLabelinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称 的本地化字符串。
        /// </summary>
        internal static string FvscLabelPname {
            get {
                return ResourceManager.GetString("FvscLabelPname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描批次码 的本地化字符串。
        /// </summary>
        internal static string Fvsclabelscan {
            get {
                return ResourceManager.GetString("Fvsclabelscan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准批次码 的本地化字符串。
        /// </summary>
        internal static string Fvsclabelstand {
            get {
                return ResourceManager.GetString("Fvsclabelstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开扫码枪 的本地化字符串。
        /// </summary>
        internal static string Fvscopensc {
            get {
                return ResourceManager.GetString("Fvscopensc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产设置 的本地化字符串。
        /// </summary>
        internal static string groupBox {
            get {
                return ResourceManager.GetString("groupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品型号： 的本地化字符串。
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产时间: 的本地化字符串。
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品条码： 的本地化字符串。
        /// </summary>
        internal static string label3 {
            get {
                return ResourceManager.GetString("label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码模板选择 的本地化字符串。
        /// </summary>
        internal static string label4 {
            get {
                return ResourceManager.GetString("label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【数据管理】 的本地化字符串。
        /// </summary>
        internal static string MenuBarcode {
            get {
                return ResourceManager.GetString("MenuBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【数据查看】 的本地化字符串。
        /// </summary>
        internal static string MenuData {
            get {
                return ResourceManager.GetString("MenuData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [条码设置] 的本地化字符串。
        /// </summary>
        internal static string MenuItemBarcode {
            get {
                return ResourceManager.GetString("MenuItemBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [最小化] 的本地化字符串。
        /// </summary>
        internal static string MenuItemMin {
            get {
                return ResourceManager.GetString("MenuItemMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [网络数据] 的本地化字符串。
        /// </summary>
        internal static string MenuItemNet {
            get {
                return ResourceManager.GetString("MenuItemNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员设置 的本地化字符串。
        /// </summary>
        internal static string MenuItemPerson {
            get {
                return ResourceManager.GetString("MenuItemPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品设置 的本地化字符串。
        /// </summary>
        internal static string MenuItemProduct {
            get {
                return ResourceManager.GetString("MenuItemProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据追溯 的本地化字符串。
        /// </summary>
        internal static string MenuItemReview {
            get {
                return ResourceManager.GetString("MenuItemReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 追溯设置 的本地化字符串。
        /// </summary>
        internal static string MenuItemReviewData {
            get {
                return ResourceManager.GetString("MenuItemReviewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【产线管理】 的本地化字符串。
        /// </summary>
        internal static string MenuProduct {
            get {
                return ResourceManager.GetString("MenuProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【系统】 的本地化字符串。
        /// </summary>
        internal static string MenuSystem {
            get {
                return ResourceManager.GetString("MenuSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划产量： 的本地化字符串。
        /// </summary>
        internal static string Mlabel5 {
            get {
                return ResourceManager.GetString("Mlabel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产型号打印设置 的本地化字符串。
        /// </summary>
        internal static string Mlabel6 {
            get {
                return ResourceManager.GetString("Mlabel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 档次号： 的本地化字符串。
        /// </summary>
        internal static string Mlabel7 {
            get {
                return ResourceManager.GetString("Mlabel7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描批次码 的本地化字符串。
        /// </summary>
        internal static string MtoolStripMI {
            get {
                return ResourceManager.GetString("MtoolStripMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string pbtnAdd {
            get {
                return ResourceManager.GetString("pbtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string pbtnDelete {
            get {
                return ResourceManager.GetString("pbtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string pbtnEdit {
            get {
                return ResourceManager.GetString("pbtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品 的本地化字符串。
        /// </summary>
        internal static string pcheckBox {
            get {
                return ResourceManager.GetString("pcheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名 的本地化字符串。
        /// </summary>
        internal static string plabel1 {
            get {
                return ResourceManager.GetString("plabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序 的本地化字符串。
        /// </summary>
        internal static string plabel2 {
            get {
                return ResourceManager.GetString("plabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        internal static string plabel3 {
            get {
                return ResourceManager.GetString("plabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工位: 的本地化字符串。
        /// </summary>
        internal static string plabel4 {
            get {
                return ResourceManager.GetString("plabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划产量 的本地化字符串。
        /// </summary>
        internal static string plan {
            get {
                return ResourceManager.GetString("plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码查找 的本地化字符串。
        /// </summary>
        internal static string RbtnSearch {
            get {
                return ResourceManager.GetString("RbtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string RbtnToExcel {
            get {
                return ResourceManager.GetString("RbtnToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间区间查找 的本地化字符串。
        /// </summary>
        internal static string Rbutton1 {
            get {
                return ResourceManager.GetString("Rbutton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用追溯 的本地化字符串。
        /// </summary>
        internal static string RcheckBox1 {
            get {
                return ResourceManager.GetString("RcheckBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string RDbtnOK {
            get {
                return ResourceManager.GetString("RDbtnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码 的本地化字符串。
        /// </summary>
        internal static string RDcode {
            get {
                return ResourceManager.GetString("RDcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        internal static string RDdata {
            get {
                return ResourceManager.GetString("RDdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线上工位 的本地化字符串。
        /// </summary>
        internal static string RDlabel30 {
            get {
                return ResourceManager.GetString("RDlabel30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线下工位 的本地化字符串。
        /// </summary>
        internal static string RDlabel31 {
            get {
                return ResourceManager.GetString("RDlabel31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工位 的本地化字符串。
        /// </summary>
        internal static string RDstation {
            get {
                return ResourceManager.GetString("RDstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按完成时间查找 的本地化字符串。
        /// </summary>
        internal static string Rgroup1 {
            get {
                return ResourceManager.GetString("Rgroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码: 的本地化字符串。
        /// </summary>
        internal static string Rlabel2 {
            get {
                return ResourceManager.GetString("Rlabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间区间 的本地化字符串。
        /// </summary>
        internal static string Rlabel4 {
            get {
                return ResourceManager.GetString("Rlabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加/更新 的本地化字符串。
        /// </summary>
        internal static string SPCbtnSave {
            get {
                return ResourceManager.GetString("SPCbtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品代号 的本地化字符串。
        /// </summary>
        internal static string SPClabel2 {
            get {
                return ResourceManager.GetString("SPClabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码前缀 的本地化字符串。
        /// </summary>
        internal static string SPClabel3 {
            get {
                return ResourceManager.GetString("SPClabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string UbtnAdd {
            get {
                return ResourceManager.GetString("UbtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string UbtnDelete {
            get {
                return ResourceManager.GetString("UbtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string UbtnEdit {
            get {
                return ResourceManager.GetString("UbtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string Ulabel1 {
            get {
                return ResourceManager.GetString("Ulabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string Ulabel2 {
            get {
                return ResourceManager.GetString("Ulabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 级别 的本地化字符串。
        /// </summary>
        internal static string Ulabel4 {
            get {
                return ResourceManager.GetString("Ulabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [生产看板] 的本地化字符串。
        /// </summary>
        internal static string 生产看板ToolStripMenuItem {
            get {
                return ResourceManager.GetString("生产看板ToolStripMenuItem", resourceCulture);
            }
        }
    }
}
